export const ENGINE_FIELD_TO_CAT: Record<string, string> = {
  // Primary fields (extracted from RFQ description/columns)
  valve_type:     'valve_type',
  size:           'size',
  pressure_class: 'pressure_class',
  moc:            'moc',
  trim:           'trim',
  trim_number:    'trim_number',
  end_type:       'end_type',
  operator:       'operator',
  bolting:        'bolting',
  gasket:         'gasket',
  packing:        'packing',
  model:          'model',
  standard:       'standard',
  service:        'service',

  // Secondary / output fields
  certification:   'certification',
  bypass:          'bypass',
  actuator:        'actuator',
  overlays:        'overlays',
  accessories:     'accessories',
  bolting_coating: 'bolting_coating',
  pup_piece_length:'pup_piece_length',
  pup_piece_moc:   'pup_piece_moc',
  special_req:     'special_req',
  special_test:    'special_test',
  spring:          'spring',
  stem_extension:  'stem_extension',
  support_foot:    'support_foot',
  tmbv_drain_vent: 'tmbv_drain_vent',
  tmbv_sealant:    'tmbv_sealant',
  others:          'others',
};

export const VALVE_TYPE_ALIASES: Record<string, string> = {
  'gate':                     'Gate Valve',
  'gtv':                      'Gate Valve',
  'gate valve':               'Gate Valve',
  'slab gate':                'Gate Valve',
  'wedge gate':               'Gate Valve',
  'globe':                    'Globe Valve',
  'gb':                       'Globe Valve',
  'glv':                      'Globe Valve',
  'globe valve':              'Globe Valve',
  'y globe':                  'Globe Valve - Y Type',
  'y type globe':             'Globe Valve - Y Type',
  'y-type globe':             'Globe Valve - Y Type',
  'globe y':                  'Globe Valve - Y Type',
  'y-body globe':             'Globe Valve - Y Type',
  'butterfly':                'Butterfly Valve',
  'btv':                      'Butterfly Valve',
  'bfv':                      'Butterfly Valve',
  'butterfly valve':          'Butterfly Valve',
  'di butterfly':             'Butterfly Valve',
  'lug butterfly':            'Butterfly Valve',
  'wafer butterfly':          'Butterfly Valve',
  'ball valve':               'Floating Ball Valve',
  'fbv':                      'Floating Ball Valve',
  'floating ball':            'Floating Ball Valve',
  'floating ball valve':      'Floating Ball Valve',
  'ball':                     'Floating Ball Valve',
  'tmbv':                     'Trunnion Mounted Ball Valve',
  'trunnion ball':            'Trunnion Mounted Ball Valve',
  'trunnion mounted ball':    'Trunnion Mounted Ball Valve',
  'trunnion mounted ball valve': 'Trunnion Mounted Ball Valve',
  'check valve':              'Check Valve - Swing Type',
  'swing check':              'Check Valve - Swing Type',
  'check valve swing':        'Check Valve - Swing Type',
  'swinging check':           'Check Valve - Swing Type',
  'cv':                       'Check Valve - Swing Type',
  'dual plate check':         'Check Valve - Dual Plate Type',
  'dual plate':               'Check Valve - Dual Plate Type',
  'double disc check':        'Check Valve - Dual Plate Type',
  'wafer check':              'Check Valve - Dual Plate Type',
  'tilting disc check':       'Check Valve - Tilting Disc',
  'tilting disc':             'Check Valve - Tilting Disc',
  'tilting check':            'Check Valve - Tilting Disc',
  'lift check ball':          'Lift Check Valve - Ball Type',
  'ball check':               'Lift Check Valve - Ball Type',
  'lift check valve ball':    'Lift Check Valve - Ball Type',
  'lift check piston':        'Lift Check Valve - Piston Type',
  'piston check':             'Lift Check Valve - Piston Type',
  'lift check valve piston':  'Lift Check Valve - Piston Type',
};

export const CLASS_ALIASES: Record<string, string> = {
  '150':          'CLASS 150',
  '150#':         'CLASS 150',
  'cl150':        'CLASS 150',
  'cl.150':       'CLASS 150',
  'class150':     'CLASS 150',
  'class 150':    'CLASS 150',
  'ansi 150':     'CLASS 150',
  '300':          'CLASS 300',
  '300#':         'CLASS 300',
  'cl300':        'CLASS 300',
  'cl.300':       'CLASS 300',
  'class 300':    'CLASS 300',
  '600':          'CLASS 600',
  '600#':         'CLASS 600',
  'cl600':        'CLASS 600',
  'cl.600':       'CLASS 600',
  'class 600':    'CLASS 600',
  '800':          'CLASS 800',
  '800#':         'CLASS 800',
  'cl800':        'CLASS 800',
  'cl.800':       'CLASS 800',
  'class 800':    'CLASS 800',
  '900':          'CLASS 900',
  '900#':         'CLASS 900',
  'cl900':        'CLASS 900',
  'class 900':    'CLASS 900',
  '1500':         'CLASS 1500',
  '1500#':        'CLASS 1500',
  'cl1500':       'CLASS 1500',
  'class 1500':   'CLASS 1500',
  '2500':         'CLASS 2500',
  '2500#':        'CLASS 2500',
  'cl2500':       'CLASS 2500',
  'class 2500':   'CLASS 2500',
};

export const MOC_ALIASES: Record<string, string> = {
  'wcb':            'ASTM A216 Gr.WCB',
  'a216 wcb':       'ASTM A216 Gr.WCB',
  'carbon steel':   'ASTM A216 Gr.WCB',
  'cs':             'ASTM A216 Gr.WCB',
  'a105':           'ASTM A105',
  'astm a105':      'ASTM A105',
  'a105n':          'ASTM A105N',
  'ss316':          'ASTM A182 Gr.F316',
  '316':            'ASTM A182 Gr.F316',
  'f316':           'ASTM A182 Gr.F316',
  'ss316l':         'ASTM A182 Gr.F316L',
  '316l':           'ASTM A182 Gr.F316L',
  'f316l':          'ASTM A182 Gr.F316L',
  'ss304':          'ASTM A182 Gr.F304',
  '304':            'ASTM A182 Gr.F304',
  'f304':           'ASTM A182 Gr.F304',
  'ss304l':         'ASTM A182 Gr.F304L',
  '304l':           'ASTM A182 Gr.F304L',
  'f11':            'ASTM A182 Gr.F11 CL.2',
  'f22':            'ASTM A182 Gr.F22 CL.3',
  'f5':             'ASTM A182 Gr.F5',
  'f9':             'ASTM A182 Gr.F9',
  'f91':            'ASTM A182 Gr.F91',
  'wc6':            'ASTM A217 Gr.WC6',
  'wc9':            'ASTM A217 Gr.WC9',
  'c5':             'ASTM A217 Gr.C5',
  'c12':            'ASTM A217 Gr.C12',
  'c12a':           'ASTM A217 Gr.C12A',
  'duplex':         'ASTM A182 Gr.F51',
  'f51':            'ASTM A182 Gr.F51',
  'f53':            'ASTM A182 Gr.F53',
  'super duplex':   'ASTM A182 Gr.F53',
  'inconel':        'ASTM B564 UNS N06625',
  'inconel 625':    'ASTM B564 UNS N06625',
  'monel':          'ASTM B564 UNS N04400',
  'monel 400':      'ASTM B564 UNS N04400',
  'hastelloy c276': 'ASTM B564 UNS N10276',
  'hastelloy':      'ASTM B564 UNS N10276',
  'titanium':       'ASTM B381 Gr.F2',
  'ltcs':           'ASTM A350 Gr.LF2',
  'lf2':            'ASTM A350 Gr.LF2',
  'lcb':            'ASTM A352 Gr.LCB',
  'cf8m':           'ASTM A351 Gr.CF8M',
  'cf8':            'ASTM A351 Gr.CF8',
  'cf3m':           'ASTM A351 Gr.CF3M',
};

export const END_TYPE_ALIASES: Record<string, string> = {
  'bwe':            'ASME B16.25 BWE',
  'butt weld':      'ASME B16.25 BWE',
  'buttweld':       'ASME B16.25 BWE',
  'bw':             'ASME B16.25 BWE',
  'rf':             'ASME B16.5 RF',
  'raised face':    'ASME B16.5 RF',
  'rtj':            'ASME B 16.5 FE – RTJ',
  'ring joint':     'ASME B 16.5 FE – RTJ',
  'ff':             'ASME B16.5 FF',
  'flat face':      'ASME B16.5 FF',
  'swe':            'SWE - CL3000',
  'socket weld':    'SWE - CL3000',
  'screwed':        'SWE - NPT',
  'npt':            'SWE - NPT',
};

export const OPERATOR_ALIASES: Record<string, string> = {
  'gear':               'Gear Unit - Handwheel Operated',
  'gear operator':      'Gear Unit - Handwheel Operated',
  'gear unit':          'Gear Unit - Handwheel Operated',
  'handwheel':          'Handwheel Operated',
  'hw':                 'Handwheel Operated',
  'hand wheel':         'Handwheel Operated',
  'chain wheel':        'Chain Wheel',
  'pneumatic':          'Pneumatic Actuator - Double Acting',
  'pneumatic da':       'Pneumatic Actuator - Double Acting',
  'pneumatic sa':       'Pneumatic Actuator - Spring Return',
  'spring return':      'Pneumatic Actuator - Spring Return',
  'electric':           'Electrical Actuator - Direct Mounted',
  'electrical':         'Electrical Actuator - Direct Mounted',
  'electro pneumatic':  'Electro Pneumatic Actuator',
  'bare stem':          'Bare Stem - Double D',
  'lever':              'Lever Operated',
  'lever operated':     'Lever Operated',
};

export const BOLTING_ALIASES: Record<string, string> = {
  'b7/2h':            'ASTM A193 Gr.B7 / ASTM A194 Gr.2H',
  'b7 2h':            'ASTM A193 Gr.B7 / ASTM A194 Gr.2H',
  'a193 b7':          'ASTM A193 Gr.B7 / ASTM A194 Gr.2H',
  'b8/8':             'ASTM A193 Gr.B8 CL.1 / ASTM A194 Gr.8',
  'b8m':              'ASTM A193 Gr.B8M CL.1 / ASTM A194 Gr.8M',
  'b16':              'ASTM A193 Gr.B16 / ASTM A194 Gr.16',
  'duplex bolting':   'ASTM A182 Gr.F51 / ASTM A194 Gr.8M',
  'l7':               'ASTM A193 Gr.L7 / ASTM A194 Gr.7',
};

export const SIZE_ALIASES: Record<string, string> = {
  "1/2": "0.5",
  "0.5": "0.5",
  "15mm": "0.5",
  "dn15": "0.5",
  "½": "0.5",
  "half inch": "0.5",
  "0.5 inch": "0.5",
  "3/4": "0.75",
  "0.75": "0.75",
  "20mm": "0.75",
  "dn20": "0.75",
  "¾": "0.75",
  "three quarter": "0.75",
  "1\"": "1",
  "1inch": "1",
  "1 inch": "1",
  "25mm": "1",
  "dn25": "1",
  "1.0": "1",
  "one inch": "1",
  "1.5": "1.5",
  "1-1/2": "1.5",
  "40mm": "1.5",
  "dn40": "1.5",
  "one and half": "1.5",
  "2\"": "2",
  "2inch": "2",
  "2 inch": "2",
  "50mm": "2",
  "dn50": "2",
  "2.0": "2",
  "3\"": "3",
  "3inch": "3",
  "3 inch": "3",
  "80mm": "3",
  "dn80": "3",
  "4\"": "4",
  "4inch": "4",
  "4 inch": "4",
  "100mm": "4",
  "dn100": "4",
  "6\"": "6",
  "6inch": "6",
  "6 inch": "6",
  "150mm": "6",
  "dn150": "6",
  "8\"": "8",
  "8inch": "8",
  "8 inch": "8",
  "200mm": "8",
  "dn200": "8",
  "10\"": "10",
  "10inch": "10",
  "10 inch": "10",
  "250mm": "10",
  "dn250": "10",
  "12\"": "12",
  "12inch": "12",
  "12 inch": "12",
  "300mm": "12",
  "dn300": "12",
  "14\"": "14",
  "350mm": "14",
  "dn350": "14",
  "16\"": "16",
  "400mm": "16",
  "dn400": "16",
  "18\"": "18",
  "450mm": "18",
  "dn450": "18",
  "20\"": "20",
  "500mm": "20",
  "dn500": "20",
  "24\"": "24",
  "600mm": "24",
  "dn600": "24",
  "30\"": "30",
  "750mm": "30",
  "dn750": "30",
  "36\"": "36",
  "900mm": "36",
  "dn900": "36",
  "42\"": "42",
  "1050mm": "42",
  "dn1050": "42",
  "48\"": "48",
  "1200mm": "48",
  "dn1200": "48"
};

export const STANDARD_ALIASES: Record<string, string> = {
  "api600": "API 600",
  "api 600": "API 600",
  "api602": "API 602",
  "api 602": "API 602",
  "api603": "API 603",
  "api 603": "API 603",
  "api6d": "API 6D",
  "api 6d": "API 6D",
  "api608": "API 608",
  "api 608": "API 608",
  "api609": "API 609",
  "api 609": "API 609",
  "bs1873": "BS 1873",
  "bs 1873": "BS 1873",
  "bs5351": "BS 5351",
  "bs 5351": "BS 5351",
  "bs5352": "BS 5352",
  "bs 5352": "BS 5352",
  "b16.34": "ASME B16.34",
  "asme b16.34": "ASME B16.34",
  "b1634": "ASME B16.34",
  "iso17292": "ISO 17292",
  "iso 17292": "ISO 17292"
};

export const TRIM_ALIASES: Record<string, string> = {
  "full bore": "Full Bore",
  "fb": "Full Bore",
  "full port": "Full Bore",
  "fp": "Full Bore",
  "reduced bore": "Reduced Bore",
  "rb": "Reduced Bore",
  "reduced port": "Reduced Bore",
  "rp": "Reduced Bore",
  "ss316 trim": "SS316",
  "316 trim": "SS316",
  "stainless trim": "SS316",
  "stellite": "Stellite",
  "hardfaced": "Stellite",
  "hard faced": "Stellite",
  "stellited": "Stellite",
  "13cr trim": "13Cr",
  "13 cr": "13Cr",
  "13 chrome": "13Cr"
};

export const ALIAS_MAP: Record<string, Record<string, string>> = {
  valve_type:     VALVE_TYPE_ALIASES,
  pressure_class: CLASS_ALIASES,
  moc:            MOC_ALIASES,
  end_type:       END_TYPE_ALIASES,
  operator:       OPERATOR_ALIASES,
  bolting:        BOLTING_ALIASES,
  size:           SIZE_ALIASES,
  standard:       STANDARD_ALIASES,
  trim:           TRIM_ALIASES,
};

export function matchLayer1(rfqValue: string, catalogueEntries: string[], category: string): string | null {
  const rfqLower = rfqValue.toLowerCase().trim();
  const aliasMap = ALIAS_MAP[category] || {};

  // Direct exact match first
  for (const entry of catalogueEntries) {
    if (entry.toLowerCase().trim() === rfqLower) return entry;
  }

  // Find canonical from alias map
  const canonical = aliasMap[rfqLower] || rfqValue;
  
  // Check if canonical exists in user's catalogue
  const catalogueMatch = catalogueEntries.find(
    e => e.toLowerCase().trim() === canonical.toLowerCase().trim()
  );
  
  if (catalogueMatch) {
    return catalogueMatch;
  }

  // If not found, we can also check if the canonical is an alias for something in the catalogue
  for (const entry of catalogueEntries) {
    const entryCanonical = aliasMap[entry.toLowerCase().trim()] || entry;
    if (entryCanonical.toLowerCase().trim() === canonical.toLowerCase().trim()) {
      return entry;
    }
  }

  return null;
}
